name: task_manager
description:  Manager Flutter project.
publish_to: ''

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.2
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf