name: task_manager
description: A Simple Task Manager Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  http: ^1.1.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf